name: Build and Deploy NestJS Backend to Azure

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build

      # SOLO subir archivos necesarios
      - name: Prepare deployment package
        run: |
          mkdir deploy
          cp -r dist deploy/
          cp package.json deploy/
          cp package-lock.json deploy/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-app
          path: backend/deploy

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: backend-app
          path: .

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'proyecto-final-api-ivan'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: .
